[package]
name = "mock-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
serde_json = "1.0.112"
tokio = { version = "1.35.1", features = ["full"] }
warp = "0.3.6"
