[package]
name = "handle-errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.23"
reqwest-middleware = "0.2.4"
tracing = { version = "0.1.40", features = ["log"] }
warp = "0.3.5"
